import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-slate-50 relative bg-black h-screen flex items-center`}
      >
        <a
          href="https://github.com/CodeTorso/embla-carousel"
          className="absolute top-4 left-4"
        >
          Github
        </a>
        {children}
      </body>
    </html>
  );
}
